### ISSUE TITLE
The reputation is not returned to the client

### ISSUE THREAD

**Issue by thewayofvikings** [mohlcyber/McAfee-TIE-multi-sandbox#2]
During testing we encountered the problem that the reputation is not returned to the client. But if we change the reputation setting as follows it works without problems.

```
tie_client.set_external_file_reputation( 
    level,    
    {HashType.MD5: md5, HashType.SHA1: sha1, HashType.SHA256: sha256},    
    filename=filename,  
    comment="External Reputation set from {}".format(sandbox),  
 )
```

See the example from https://opendxl.github.io/opendxl-tie-client-python/pydoc/dxltieclient.client.html?highlight=set_file_reputation#dxltieclient.client.TieClient.set_file_reputation .

**Comment by mohlcyber** [comment]
Thanks for the note. Seems this one fall through the cracks. I made the adjustments. Thanks for improving it.
